[package]
name = "example-webserver-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.128"
serde = { version = "1.0.209", features = ["derive"] }
rand = "0.9.0-alpha.2"
